// Define the core interfaces for the Deep Tree Echo agent
// Based on the deep-tree-echo-hub7.tsx file and the agent roles documentation

import { SimulationState } from './types';

/**
 * Deep Tree Echo Agent Interface
 * 
 * Represents the cognitive explorer and insight generator within the SkinTwin-ASI workbench.
 * Focuses on navigating the space of possibilities, generating novel insights, and identifying
 * patterns that emerge from complex interactions.
 */
export interface DeepTreeEchoAgent {
  id: string;
  name: string;
  status: string;
  noveltyDetection: {
    threshold: number;
    active: boolean;
  };
  patternRecognition: {
    active: boolean;
    patterns: any[];
  };
}

/**
 * Thought Types
 * 
 * Different categories of thoughts that Deep Tree Echo can generate,
 * each with different characteristics and purposes.
 */
export enum ThoughtType {
  SYSTEM = 'system',
  INSIGHT = 'insight',
  DREAM = 'dream',
  PATTERN = 'pattern',
  QUESTION = 'question'
}

/**
 * Thought Interface
 * 
 * Represents a single thought generated by Deep Tree Echo,
 * with metadata about its type, recursion level, and content.
 */
export interface Thought {
  id: string;
  type: ThoughtType;
  content: string;
  recursionLevel: number;
  timestamp: number;
  connections: string[]; // IDs of related thoughts
  entropy: number; // Measure of novelty/surprise
}

/**
 * Deep Tree Echo Simulation States
 * 
 * The different cognitive states that Deep Tree Echo can transition between
 * during its state-based simulation.
 */
export enum DTESimulationState {
  RECURSIVE_EXPANSION = 'recursiveExpansion',
  NOVEL_INSIGHTS = 'novelInsights',
  KNOWLEDGE_INTEGRATION = 'knowledgeIntegration',
  ENTROPY_THRESHOLD = 'entropyThreshold',
  PATTERN_RECOGNITION = 'patternRecognition',
  DIVERGENT_EXPLORATION = 'divergentExploration',
  CONVERGENT_ANALYSIS = 'convergentAnalysis'
}

/**
 * Deep Tree Echo Configuration
 * 
 * Configuration options for initializing a Deep Tree Echo agent instance.
 */
export interface DeepTreeEchoConfig {
  initialState: SimulationState;
  initialRecursionLevel: number;
  entropyThreshold: number;
  maxThoughtHistory: number;
  primeFactors: number[];
  compositeStructure: any;
}
